services:
  lightshow:
    image: ghcr.io/bernardteske/lightshow:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lightshow
    ports:
      - "3000:3000"
    volumes:
      - ./programmes:/app/programmes
    restart: unless-stopped
    environment:
      - PORT=3000

